### ISSUE TITLE
Typescript compiler issue & conflict

### ISSUE THREAD

**Issue by ShMcK** [Urigo/Meteor-Angular2#1]
Typescript is not running on the backend.

     - client
       \- app.ts  ✓
     - model
       \- parties.ts ✗

However, changing the backend to Javascript works.

     - client
       \- app.ts  ✓
     - model
       \- parties.js ✓

If another typescript compiler package is added, there is a conflict.

     While building the application:
       error: conflict: two packages included in the app, hansoft:typescript and barbatus:angular2, are both trying to handle .ts

A lot of the benefits of Typescript are lost when the same types can't be applied to the full application.

**Comment by ShMcK** [comment]
A few possible workarounds for now:
- use your IDE's TS compiler, set the scope to ignore the client (eg. Webstorm)
- run a TS watcher process in a separate terminal, in your tsconfig.json set `exclude: ['client']`

**Comment by dalcib** [comment]
@ShMcK, the barbatus:angular2 compiles both server and client.

However, to use Typescript in the server you need  define a js file with main import, like this:

```
//server/boot.js

System.import('server/loadParties');
```

or use one file to all main imports (server, model and client), removing System.import from the index.html:

```
//boot.js

System.import('model/parties');

if (Meteor.isClient) {
    System.import('client/parties-list');   
} else {
    System.import('server/loadParties');
}
```

**Comment by dalcib** [comment]
You need also a package like [systemjs:systemjs](https://atmospherejs.com/systemjs/systemjs) wich export ```System``` to the server.

**Comment by ShMcK** [comment]
That's a much better solution.

Is there any way to automate the `/server` file paths, since any `.ts` file not in the client would get imported?

**Comment by barbatus** [comment]
@ShMcK As it was already mentioned above, you need to import some main SystemJS module(s) manually same way as for the client to make it running. systemjs:systemjs actually is already included in the package for server side too, so there is no problem here. Problem is in another place: SystemJS modules imported asynchronously so they will run eventually out of Meteor context and you'll end up getting exceptions like 'Server-side module code not running within a Fiber'. I wasn't able to find a fix for this even with ````Meteor.bindEnvironment````. So I've come up with another approach for now (or maybe we'll leave it permanently): one always needs to create server's ````main.ts```` file which the only one will  be imported synchronously (i.e. in Meteor context) and executed automatically. So one needs to keep there code he wants to be executed at first and/or exports outside other modules. Please, check out new version of Parties demo.

About conflicts with other TypeScripts packages. Some time ago I didn't find any TypeScript package up to date or that's configurable outside (to make use of SystemJS), so I decided to support TypeScript as part of the package. In future, I guess, we'll switch to some good package when it appears.

**Comment by ShMcK** [comment]
So everything works, but users choosing Typescript on the backend must manually `import`/`export` modules. I'm happy with that work that solution.
