### ISSUE TITLE
Depending on wrong version of barbatus:angular2

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/Meteor-Angular2#10]
The package is depending on barbatus:angular2~0.5.0, while the last actual version is 0.4.6.

**Comment by barbatus** [comment]
@MilosStanic 
I think actual version is right, it's 0.5.0 which was released couple of days ago.
 0.5.0v, though, has the issue with cosmos:browserify package@0.7.0, so I just reverted it back to cosmos:browserify@0.5.0. Please check it out now.

**Comment by MilosStanic** [comment]
As I already said in that other place, it works now. Thanks again.
