### ISSUE TITLE
getting error if using: meteor add urigo:angular2-meteor

### ISSUE THREAD

**Issue by thisisole** [Urigo/Meteor-Angular2#11]
this is the reply I get:

 => Errors while parsing arguments:

While adding package urigo:angular2-meteor:
error: no such package

**Comment by MilosStanic** [comment]
you should install the package by git cloning this repo to the /packages subdir of your app dir. Then run meteor add urigo:angular2-meteor.
Then edit the package.js in the cloned git and change dependency barbatus:angular2~0.5.0 to barbatus:angular2~0.4.6

Then run meteor, and it should all work, hopefully ;)

**Comment by thisisole** [comment]
thx for this tipp, but then the documention should be changed, shouldn't it??? 

I am a beginner and nothing is more frustrating like a non working documentation... and everything I find is not working (this http://angular-meteor.com/tutorials/angular2/bootstrapping for example isnt working too...)

**Comment by MilosStanic** [comment]
No problem, I just wasted 2 days, too. This package hasn't actually been released yet. And the docs haven't been updated.

**Comment by Stivfk** [comment]
This issue has been addressed twice already. See here
https://github.com/Urigo/Meteor-Angular2/issues/8
https://github.com/Urigo/Meteor-Angular2/issues/3

I think the doc should be updated to notify users of the status of this package and how to eventually run it without hassle.

**Comment by barbatus** [comment]
@Stivfk Ok, makes sense. Just updated the readme.

**Comment by alecperkey** [comment]
@MilosStanic, regarding your comment:

"you should install the package by git cloning this repo to the /packages subdir of your app dir. Then run meteor add urigo:angular2-meteor."

If you have a minute to help me out please see this: http://i.imgur.com/Nj5z39n.png

I did not initially have this socially/packages directory so I created it and cloned this repo into it. But I think meteor add is not looking in the socially/packages. 

I did search meteor api with no luck. Also found this https://dweldon.silvrback.com/local-packages but it seems that is beyond what I'm trying to do (it seems it's for creating a library of local packages for many apps to reference)
