### ISSUE TITLE
Add requirement for `main.ts` on the server in README.md

### ISSUE THREAD

**Issue by sclausen** [Urigo/Meteor-Angular2#12]
You can't choose another main-module than main.ts on the server, because it is hardcoded in barbatus:angular2.

**Comment by barbatus** [comment]
Yes, I'll add it for sure. Though, presence of main.ts is not required like you said; if it's there it'll be imported if it's not you'll need to import another module manually.

**Comment by sclausen** [comment]
How do you import another module on the server to be executed at startup?

**Comment by barbatus** [comment]
Same way you'd do it for client side:
add main.js with
````
Meteor.startup(function(){
 System.import('server/foo').await();
})
````

**Comment by sclausen** [comment]
Hmm, maybe I got the wrong idea how stuff works, bu if you don't create a `main.ts` on the server, no code will be executed there, so where would you define this import?

**Comment by sclausen** [comment]
Maybe I slowly got it. js files are executed normally without being registered as system.js modules, so 
I could create a foo.js on the server with
``` javascript
Meteor.startup(function(){
 System.import('server/foo').await();
})
```
right!?

**Comment by barbatus** [comment]
@sclausen yes, exactly

**Comment by sclausen** [comment]
Hmm, but the server doesn't know about system.js…
```
While processing files with barbatus:angular2 (for target
   os.linux.x86_64):
   /server/notmain.ts:16:2: Cannot find name 'System'.
```
Do I have to add systemjs:systemjs to my project for myself, or am I doing something still wrong?

**Comment by barbatus** [comment]
You seem to be missing something. If there wasn't System defined on the server, it wouldn't work even with `main.ts`.

**Comment by barbatus** [comment]
systemjs:systemjs should be added to your app by the package.

**Comment by sclausen** [comment]
Okay, I don't know, what I did wrong before. Everything now works as expected. The custom import in a server-side js-file works like a charm.

**Comment by barbatus** [comment]
Use System in pure .js-files, in .ts ones you don't need it

**Comment by sclausen** [comment]
Yeah I know, I got that before writing my third comment in this issue, but I did something wrong and was confused about the server not knowing anything about the systemjs:systemjs you added in barbatus:angular2… Thanks for clarification! :relaxed:
