### ISSUE TITLE
upgrade to angular@2.0.0-alpha.38 not possible

### ISSUE THREAD

**Issue by sclausen** [Urigo/Meteor-Angular2#15]
We have to wait for a fix for meteor/meteor#4985, because the very old npm meteor is using, has to be upgraded.

**Comment by MilosStanic** [comment]
Anyway, alpha.39 is out, and they say alpha.38 was pretty buggy.

**Comment by sclausen** [comment]
But the problem persists :wink:
 angular@2.0.0-alpha.39 depends on `@reactivex/rxjs@0.0.0-prealpha.3`.
