### ISSUE TITLE
Heads up: changes in DI pattern in next Angular2 release 

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/Meteor-Angular2#18]
Please find updated docs here: 

https://github.com/thoughtram/blog/commit/599c6c0dc726cbf34428ed067d48fcaddb3a52c3

I don't know if this affects meteor-angular2 in any way, but I'm sure it will affect the docs.

**Comment by barbatus** [comment]
Thanks for the info, Angular 2 have been updated to 42v in this package, as well as all docs and tutorial.
