### ISSUE TITLE
App not running with Meteor 1.2 rc-12

### ISSUE THREAD

**Issue by ShMcK** [Urigo/Meteor-Angular2#2]
The root application is not loaded when using Meteor 1.2 rc-12. 

No errors appear in the console.

**Comment by barbatus** [comment]
@ShMcK 
Just tested with meteor --release 1.2-rc.12, worked perfectly well.
Is there any other details maybe?

**Comment by ShMcK** [comment]
I was missing the `extends MeteorComponent` addition to the classes. You're right, it's running great.

**Comment by Stivfk** [comment]
Works fine on release candidate 14 ``` Meteor --release 1.2-rc.14 ```
