### ISSUE TITLE
Routing problems with Angular2 and Meteor

### ISSUE THREAD

**Issue by pgrm** [Urigo/Meteor-Angular2#26]
I'm going through the tutorial and am currently at step 5 with the following problems:

1. The url generated by my application has a `/null` as a prefix, such as: `http://localhost:3000/null/party/aeb1bb088d277bad72a0a10b` I get the same url when testing the tutorial code directly.
2. When I click on it I see the correct url in the browser (`http://localhost:3000/party/aeb1bb088d277bad72a0a10b`) but I can't directly open either of those urls in a new tab / window
3. So I switched temporarily to the `HashLocationStrategy` which works for both above described problems, but for some reason trying to open the link in a new tab with `cmd+click` (or `ctrl+click` on linux/window) again doesn't work. I tried Chrome, Firefox and Safari, neither worked.

I thought I was getting crazy, so I checked out the old tutorial with Angular1 which I made some time ago, and there everything worked:

1. I had correct HTLM5 urls
2. I could open a random url from that app in a new tab / window and it opened the correct view
3. `cmd+click` (`ctrl+click`) worked like it does on any other website

I couldn't find anything on this topic, is this a known issue? Any idea how to fix it?

**Comment by barbatus** [comment]
yes, there is an issue with that.

The first thing /null seems a bug in Angular 2 router since I looked closely into and still have no idea why it happens. Anyways, links work so it can be put off for time being. 

The second one I forget to fix for a long time. You will need to make templateUrl to be an absolute path instead of relative [here](https://github.com/Urigo/meteor-angular2.0-socially/blob/master/client/party-details/party-details.ts#L18), or in other words place slash '/' in front of client.

**Comment by pgrm** [comment]
Thx, I've found also the problem with 3 in the meanwhile - router-link listens at the click event, so it doesn't really create just an a tag but it listens at the click events. In long term and for bigger applications I think this is quite annoying if I can't just say `cmd+click` to get a new tab. 

Do you know if there is a way to do this with the new router?

**Comment by pgrm** [comment]
Ok, found the bug with `null`

https://github.com/angular/angular/blob/b0009f03d510370d9782cf76197f95bb40d16c6a/modules/angular2/src/core/dom/browser_adapter.ts#L309

    getBaseHref(): string {
      var href = getBaseElementHref();
      if (isBlank(href)) {
        return null;
      }
      return relativePath(href);
    }

it's still using the old `<base href="/" />` syntax here

**Comment by pgrm** [comment]
And there is already a bug report in angular2: https://github.com/angular/angular/issues/5028

**Comment by barbatus** [comment]
@pgrm About cmd+click.
If you set target='"_target" it should open new page. [See] (https://github.com/angular/angular/blob/b0009f03d510370d9782cf76197f95bb40d16c6a/modules/angular2/src/router/router_link.ts#L70)

But it's been fixed recently in 2.0.0-alpha.46 ([here](https://github.com/angular/angular/commit/a69e7fe297d993522167060cad275334ac95768e)). I plan to update to this version soon.

**Comment by pgrm** [comment]
@barbatus I missed looking closer at the if condition, thx, so that means (almost) everything works - or is at least reported as a bug, that's great :+1:
