### ISSUE TITLE
Problems with reactive updates of objects

### ISSUE THREAD

**Issue by pgrm** [Urigo/Meteor-Angular2#27]
I kinda finished the tutorial and found out that I can't make updates of objects working.

When I add new items to the collection or remove existing items, 2 tabs or windows are nicely in sync. But when I modify an object and save those change, I have to reload the page. I've checked out the tutorial code and saw the same issues there as well. Any ideas?

- I'm getting the collection just via `this.parties = Parties.find();`
- I'm getting the object via: `this.party = Parties.findOne(partyId);`
- and I'm updating and object via:
````
    saveParty() {
      Parties.update(this.party._id, {
        $set: {
          name: this.party.name,
          description: this.party.description,
          location: this.party.location
        }
      });
````

**Comment by pgrm** [comment]
I've tried the approach of the sample application in this project, which uses the MongoComponent base class. It's still not working, and when I tried the provided example app, I saw the same error (when changing the objects in the database directly).

Where is the root of the problem? Cursor updates work like a charm, but object changes aren't being detected. I tried to use `this.autorun` but the function inside was only called in the beginning and never again.

**Comment by pgrm** [comment]
Hi, I still had problems with this for the couple last days and now I found out what was the problem - if you use ObjectIDs than it still doesn't work. Here a simple example which will work / and won't work depending if you use ObjectID or Meteor's random strings: https://github.com/pgrm/angular2-meteor-reactivity-test

Any idea how to get it to work with ObjectID? There is also the problem, that I need to know in my application if a collection is using strings or objectid, as for some reason Meteor doesn't let met query for a string, instead I need to create the ObjectID object. In other NodeJS applications I am and was working with, I used just strings and the mongo driver converted it accordingly. Is this maybe a known issue or a "feature" from meteors side?

**Comment by barbatus** [comment]
I potentially fix the first issue, it needs a verification though.

For the second one, you may try MongoID.idParse. For some reason, it's not used inside Collection.find of the Minimongo.

**Comment by allanlundhansen** [comment]
I am also having problems getting the autorun to work with object changes, even when Meteor random strings in DB did you get this to work? Works fine on cursors as well

**Comment by allanlundhansen** [comment]
Sorry never mind must have been tired since not thinking through autorun change on cursors vs documents. I am not sure why the example app socially uses cursors on the models though, just speaking from a pure reactive dependency perspective, and demoing the power of reactive interface updating?
