### ISSUE TITLE
Cannot use with blaze-html-templates?

### ISSUE THREAD

**Issue by basakil** [Urigo/Meteor-Angular2#29]
While following the readme to use/try angular2 in a new/plain meteor app, meteor displayed the following error even without any html file in the project:
```
           While determining active plugins:
           error: conflict: two packages included in the app (templating and urigo:angular2-meteor) are both trying to handle
           *.html
```
Removing `blaze-html-templates` solved the issue, but I guess this will prevent me using `accounts-ui` and dump its view in an angular2 template, since it depends on `blaze`. Is there a way to use it or an alternative for accounts stuff?

**Comment by barbatus** [comment]
Please, use this package https://atmospherejs.com/barbatus/ng2-meteor-accounts-ui.
You can also check out tutorial on this topic http://angular-meteor.com/tutorials/angular2/user-accounts-authentication-and-permissions
