### ISSUE TITLE
Cannot install using cli meteor add urigo:angular2-meteor

### ISSUE THREAD

**Issue by Stivfk** [Urigo/Meteor-Angular2#3]
I tried to install the package using ```meteor add urigo:angular2-meteor``` command but I got the following error:
```
While selecting package versions:
   error: unknown package in top-level dependencies: urigo:angular2-meteor
```

**Comment by barbatus** [comment]
It's not published yet. Angular2 still being changed rapidly is one of the reasons.
I think it'll happen closer to the end of September, meanwhile we'll add more useful stuff to the package.
