### ISSUE TITLE
ReferenceError when integrating CommonJS module

### ISSUE THREAD

**Issue by drewlio** [Urigo/Meteor-Angular2#34]
Firstly, I'm new to a lot of this and hope I'm just doing something silly. I'm trying to use an existing, unmodified, CommonJS module. This compiles fine with tsc v1.5.3 and runs with node.js v5.1.0 but meteor-angular2 throws the error below. 

I made this test case in the directory `server/example` of my meteor-angular2 app. I have these three files:

### myModule.js
```javascript
module.exports = {
    "foo": "I am a string",
    "bar": function() {
        return "I came from a function";
    }
};
```

### myModule.d.ts
```javascript
declare module myModule {
    export var foo: string;
    export function bar(): string;
}
export = myModule;
```

### test.ts
```javascript
/// <reference path="./myModule.d.ts" />
import m = require("./myModule");
console.log(m.foo);
```

But when meteor-angular2 starts, it throws this error:
```
W20151124-16:22:54.783(0)? (STDERR) /home/drew/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151124-16:22:54.783(0)? (STDERR) 						throw(ex);
W20151124-16:22:54.783(0)? (STDERR) 						      ^
W20151124-16:22:54.785(0)? (STDERR) ReferenceError: module is not defined
```

Is this unexpected behavior or am I doing something wrong?

**Comment by barbatus** [comment]
You'll need to use a commonjs loader to make it work. This packages comes only with the System.js loader. There exists https://atmospherejs.com/cosmos/browserify for the commonjs notation.

**Comment by drewlio** [comment]
Thank you Alex.
