### ISSUE TITLE
Adding other ng2 modules

### ISSUE THREAD

**Issue by earlsioson** [Urigo/Meteor-Angular2#39]
What is the recommended way of adding other ng2 modules that don't have a meteor package yet? For example, should I add the RouteConfig from 'angular2/router' and Http from 'angular2/http' to the NPM.depends and Npm.require settings?

**Comment by barbatus** [comment]
Angular2 modules are exposed via System.js in this package (or, to be exact, in the angular2 [package](https://github.com/barbatus/angular2), which is added transitively here). Main modules like 'core', 'common', 'browser' etc are wrapped in System modules there (you can check them [here](https://github.com/barbatus/angular2/blob/master/angular2.js)). 'http' and 'animate' are not added yet. If you want to use them, you can either create a new package in the similar manner and add it to your project or you can try Npm.require with Browserify and wrapping imports in a System module. Not sure, though, that latter is possible today; there were some limitations a couple of months ago.

**Comment by earlsioson** [comment]
@barbatus thank you for the reply. I will try wrapping any additional modules in a package similar to the samples you linked to.
