### ISSUE TITLE
How to use methods ?

### ISSUE THREAD

**Issue by DrBrooklyn** [Urigo/Meteor-Angular2#41]
Hello,

I have some problems to use method in my own validator. How I can use meteor methods with meteor-ng2 ? 

In Meteor/Ng1, we have promise but in ng2... ?

Thank you.

**Comment by Urigo** [comment]
You can just use the regular Meteor.call syntax.
In Angular 1.x we do the same now.
Please re-open if it's not clear

**Comment by DrBrooklyn** [comment]
Hello, 

I need to use methods with async validator.

What is the right way ?

Thank you!

**Comment by Urigo** [comment]
@DrBrooklyn can you post it as a general Meteor question in the Meteor forums and link to this issue?
thank you
