### ISSUE TITLE
Errors after updating

### ISSUE THREAD

**Issue by lukaszkukawski** [Urigo/Meteor-Angular2#42]
Hi,

After updating plug-ins in my hobby project, I have errors. List updated plug-ins

* barbatus:angular2                upgraded from 0.6.7_1 to 0.7.0
* barbatus:ng2-meteor-accounts     upgraded from 0.1.2 to 0.1.3_2
* barbatus:ng2-meteor-accounts-ui  upgraded from 0.1.1 to 0.1.2_1
* barbatus:ts-compilers            upgraded from 0.1.8_1 to 0.1.9_4
* barbatus:typescript              upgraded from 0.1.3_1 to 0.1.3_3
* urigo:angular2-meteor            upgraded from 0.2.7 to 0.3.1

In chrome console i have messages:

```
Uncaught SyntaxError: Unexpected token <
barbatus_angular2.js?f8d37519d7a440740ee9e03701ce42362f0c39f0:8559 Uncaught RangeError: Maximum call stack size exceeded
```

And in firefox console:
```
SyntaxError: syntax error
<!DOCTYPE html>

uncaught exception: SyntaxError: syntax error Evaluating http://localhost:3000/angular2/angular2 Error loading http://localhost:3000/client/app
```
Link to my project https://github.com/lukaszkukawski/projectManagement/tree/feature-refactor-1

Anyone can help?

**Comment by barbatus** [comment]
Hey, why not to be a bit more careful every time you going to create an issue, and check out for updates repo README at least?
There was an update in the latest Angular2 versions, there is no more angular2/angular2 namespace.

**Comment by lukaszkukawski** [comment]
Sorry, in next time i will more careful :).
Thx.
Great job in this
