### ISSUE TITLE
error: no such package

### ISSUE THREAD

**Issue by jcache** [Urigo/Meteor-Angular2#8]
After running  ```meteor add urigo:angular2-meteor``` I get the following error:

     => Errors while parsing arguments:
    
    While adding package urigo:angular2-meteor:
    error: no such package

I don't have trouble adding other packages, and I'm new to meteor, so I'm not quite sure how to proceed.
Any thoughts?

**Comment by yanickrochon** [comment]
Same thing. This is with a brand new project, with latest meteor (1.2.0.1)

**Comment by Stivfk** [comment]
This is a duplicate issue and has been addressed from here: issue https://github.com/Urigo/Meteor-Angular2/issues/3

To use this package, you can clone this repo directly in your meteor/package folder then use the command ``` meteor add urigo:angular2-meteor ```

**Comment by jcache** [comment]
That bit about cloning into ```$<my project folder>/packages``` was not in issue #3, and it's not obvious in the getting started info in the docs or SO, though I [found it](http://stackoverflow.com/questions/18159924/how-to-install-atmosphere-packages-without-meteorite) eventually. It worked perfectly!
Thanks Stivfk!
