### ISSUE TITLE
Error conflict: 2 packages handling *.html

### ISSUE THREAD

**Issue by Stivfk** [Urigo/Meteor-Angular2#9]
An error is preventing startup on ```meteor run```:
```While determining active plugins:
   error: conflict: two packages included in the app (barbatus:angular2 and templating) are both trying to handle *.html```

Using meteor v1.2.0.1 and meteor-angular2 v0.2.0

**Comment by MilosStanic** [comment]
yes, I resolved this by removing the blaze-html-templates. However, I was stuck after that, because my app can't find module 'angular2/angular2'

**Comment by Stivfk** [comment]
Thanks MilosStanic,

I'll leave it open as i think the meteor2-angular package should only handle ```*.ng.html``` rather than ```*.html``` files.

**Comment by barbatus** [comment]
@Stivfk 
I think it’s a conceptual shift here. While Blaze is a great UI package, it’s not part of Meteor’s core.
The point here - we want to make use of Blaze patterns in this Angular2 package, but, at the same, let Angular2 to be the main UI library with .html-files devoted to Angular2 as it happens in a regular (not Meteor) Angular2 app.

We could actually let Blaze along, but Meteor’s file processing is not a pipeline today.
I guess, it’ll become so in future versions and one be able to use two HTML processors at the same time.

**Comment by Stivfk** [comment]
That's great. I like the way this is going.

**Comment by Urigo** [comment]
@barbatus is right, we want to use Angular 2.0 as the main view layer for those who want to.
But we also want to let Blaze developers to migrate gradually to it so we are starting to work on it and on a migration tutorial from Blaze to Angular 2.0.
We would love some help with that, join can join the discussion here:  https://github.com/Urigo/Meteor-Angular2/issues/14
